DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS payments;

create table users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  name text not null,
  email text not null,
  phone text,
  codebtor_id bigint references users(id),
  role text default 'user' check (role in ('admin', 'user')),
  is_new_user boolean default true,
  requires_password_change boolean default false,
  last_password_change timestamptz default now(),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  preferred_language text default 'es'
);

create table loans (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) not null,
  reason text default 'No reason',
  amount numeric not null,
  interest_rate numeric not null,
  status text default 'active',
  is_request boolean default false,
  request_date timestamptz default now(),
  request_approved boolean default false,
  created_at timestamptz default now()
);

create table payments (
  id bigint generated by default as identity primary key,
  loan_id bigint references loans(id) not null,
  amount numeric not null,
  payment_date timestamptz default now()
);

-- Insert users
INSERT INTO users (username, password_hash, name, email, phone, role, is_new_user, preferred_language) VALUES
('admin', 'hashPassword', 'Administrator', 'admin@admin.com', '999-999-999', 'admin', false, 'en');